# Generated by Django 3.0.3 on 2020-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodid', models.CharField(max_length=10, unique=True)),
                ('prodname', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
