# Generated by Django 3.0.3 on 2020-03-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_searchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
