# Generated by Django 3.0.3 on 2020-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_searchapp', '0002_auto_20200316_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=1000, max_length=10),
            preserve_default=False,
        ),
    ]
