# Generated by Django 3.0.3 on 2020-03-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_searchapp', '0003_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Phone', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
