# Generated by Django 3.0.3 on 2020-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_searchapp', '0004_auto_20200317_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
