# Generated by Django 3.0.3 on 2020-04-12 16:25

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200412_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31),
        ),
    ]
