# Generated by Django 3.0.3 on 2020-04-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200412_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Should be in the format: '+999999999'", regex='^\\+?1?\\d{9,13}$')]),
        ),
    ]
