# Generated by Django 3.0.3 on 2020-04-12 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200412_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Should be in the format: '+919999999999'", regex='^\\+?1?\\d{12,13}$')]),
        ),
    ]
